### ISSUE TITLE
Doesn't Check All IDs in the List

### ISSUE THREAD

**Issue by lwooden** [abunuwas/microservice-apis#9]
Hey @abunuwas!

Just worked through this example tonight and I realized that the logic here in api.py does not check against all ID's of each order object in the list.

@app.get('/orders/{order_id}', response_model=GetOrderSchema)
def get_order(order_id: UUID):
    for order in ORDERS:
        if order['id'] == order_id:
            return order
    raise HTTPException(
        status_code=404, detail=f'Order with ID {order_id} not found'
    )

If I run the app and create more than one order through the POST route and append it to the ORDERS list, the GET /orders/{order_id} logic as-is will only check the id property of the 0 index and immediately throw 404 (NOT FOUND) if the ID you put in is not the ID of the first order you crated.  So if you perform a GET with the ID of the second item in the List. the application will say that the ID is not found when it fact it does indeed exist. The check just doesn’t proceed past the first object/index in the list.

**Comment by abunuwas** [comment]
Hi @lwooden thank you for your comment and please excuse me for my belated reply! Can you please check out the latest version of the code? I've been pushing updates recently and the most recent version works fine. It looks like this:

```python
@app.get('/orders/{order_id}', response_model=GetOrderSchema)
def get_order(order_id: UUID):
    for order in orders:
        if order['id'] == order_id:
            return order
    raise HTTPException(
        status_code=404, detail=f'Order with ID {order_id} not found'
    )
```

When copying the code, make sure the indentation is correct, as otherwise you could have an early exit from the function and therefore be in a situation where not all the IDs are checked.

Let me know if this helps!

**Comment by abunuwas** [comment]
I'm closing this ticket now. If my comment didn't help, feel free to reopen the ticket or raise a new issue! Thanks again for your comment!
